name = "FiniteMPS"
uuid = "6b572690-f317-4dad-a5fe-5fe73a0b7d42"
authors = ["qyli <liqiaoyi@itp.ac.cn>"]
version = "1.6.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SerializedElementArrays = "d3ce8812-9567-47e9-a7b5-65a6d70a3065"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AbstractTrees = "0.4.5"
KrylovKit = "0.8"
TensorKit = "0.12.1 - 0.12.7"
Reexport = "1.2.2"
SerializedElementArrays = "0.1.0"
TimerOutputs = "0.5.23"
julia = "1.9"
Graphs = "1.12"
MetaGraphs = "0.8"

